<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class View_requestd2p extends CI_Controller {
	function __construct() {
		parent::__construct();
		if($this->session->userdata('admin_valid') != true){
			redirect(base_url("index.php/admin/login"));
		}
		$this->load->model(array('web_model','view_requestd2p_model','requestd2p_model'));
	}


// VIEW LIST REQUEST D2P

	public function view_requestd2p_list (){
		$data['page']		= "l_view_requestd2p";	
		$data['view_request'] = $this->view_requestd2p_model->getAllViewRequest();
		// print_r($data['view_request']);
		// die();

		if (!empty($this->input->post('q'))){
			$data['view_request'] =  $this->view_requestd2p_model->searchViewRequest();
		}

		
		$this->load->view('admin/aaa', $data);

	}

// APPROVAL LIST REQUEST D2P

	public function approval_request_d2p($id,$id_role){
		$data = $this->requestd2p_model->getDetailRequestById($id);
		$mailContent1 = 
        	'<html>
			<table width="600" style="border: 1px solid black;">
			  <tr>
			    <td width="100%" align="center" bgcolor="#5776B7"><h1 style="color:#ffff;">D2P Request - '.$data[0]->project_name.' </h1></td>
			  </tr>
			  <tr>
			    <td align="center">
			      <table width="100%" class="table-form">
					<tr><td width="25%">Name <span style="color:red;"></span></td><td><b>'.$data[0]->name.'</b></td></tr>

					<tr><td width="25%">Project Name <span style="color:red;"></span></td><td><b>'.$data[0]->project_name.'</b></td></tr>			

					<tr><td width="25%">Project ID <span style="color:red;"></span></td><td><b>'. $data[0]->project_id.'</b></td></tr>
					
					<tr><td width="25%">Project Manager <span style="color:red;"></span></td><td><b>'. $data[0]->project_manager.'</b></td></tr>			

					<tr><td width="25%">Notes </td><td><b>'. $data[0]->keterangan.'</b></td></tr>				

					<tr><td width="25%">Date  <span style="color:red;">*</span></td><td><b>'. $data[0]->created_date.'</b></td></tr>	
		
					</td></tr>
					<tr>
					<td width="100%" align="center" bgcolor="#5776B7" style="color: #fff;" >This email is generated by stystem, we are not checking the email that have to sent to this email, please kindly open    '.base_url().' for more detailed information.</td>
				</tr>
				</table>   
			  
			</table>
			</html>';
			$mailContent2 = 
        	'<html>
			<table width="600" style="border: 1px solid black;">
			  <tr>
			    <td width="100%" align="center" bgcolor="#0be881"><h1 style="color:#ffff;">Approved Request - '.$data[0]->project_name.' </h1></td>
			  </tr>
			  <tr>
			    <td align="center">
			      <table width="100%" class="table-form">
					
					<tr><td width="25%">Project Name <span style="color:red;"></span></td><td><b>'.$data[0]->project_name.'</b></td></tr>			

					<tr><td width="25%">Project ID <span style="color:red;"></span></td><td><b>'. $data[0]->project_id.'</b></td></tr>
					
					<tr><td width="25%">Project Manager <span style="color:red;"></span></td><td><b>'. $data[0]->project_manager.'</b></td></tr>			
		
					</td></tr>
					<tr>
					<td width="100%" align="center" bgcolor="#5776B7" style="color: #fff;" >This email is generated by stystem, we are not checking the email that have to sent to this email, please kindly open    '.base_url().' for more detailed information.</td>
				</tr>
				</table>   
			  
			</table>
			</html> Good Luck';

			$mailContent3 = 
        	'<html>
			<table width="600" style="border: 1px solid black;">
			  <tr>
			    <td width="100%" align="center" bgcolor="#ffa801"><h1 style="color:#ffff;">	
					Waiting Approval GM Operation - '.$data[0]->project_name.' </h1></td>
			  </tr>
			  <tr>
			    <td align="center">
			      <table width="100%" class="table-form">
					
					<tr><td width="25%">Project Name <span style="color:red;"></span></td><td><b>'.$data[0]->project_name.'</b></td></tr>			

					<tr><td width="25%">Project ID <span style="color:red;"></span></td><td><b>'. $data[0]->project_id.'</b></td></tr>
					
					<tr><td width="25%">Project Manager <span style="color:red;"></span></td><td><b>'. $data[0]->project_manager.'</b></td></tr>			
		
					</td></tr>
					<tr>
					<td width="100%" align="center" bgcolor="#5776B7" style="color: #fff;" >This email is generated by stystem, we are not checking the email that have to sent to this email, please kindly open    '.base_url().' for more detailed information.</td>
				</tr>
				</table>   
			  
			</table>
			</html> Good Luck';


		// print_r($id.'-'.$id_role); die();
		if($id_role == '3'){
			$status = '4';
			$to = 'rizalmuhammad911@gmail.com';
			$to2 = $data[0]->email;
			$message = $mailContent1;
			$message2 = $mailContent3;
			$subject = 'D2P Request - '.$data[0]->project_name.'';
			//$this->emailSend($to,$message,$subject);
			//$this->emailSend($to2,$message2,$subject);
			
		}elseif($id_role == '4'){
			$status = '5';
			$to = $data[0]->email;
			$message = $mailContent2;
			$subject = 'D2P Request - APPROVAL'.$data[0]->project_name.'';
			//$this->emailSend($to,$message,$subject);
		}
		$this->view_requestd2p_model->approval_request_d2p($id,$status);
		
		redirect('index.php/view_requestd2p/view_requestd2p_list');	
	}

// REJECT LIST REQUEST D2P

	public function reject_request_d2p($id,$id_role){
		$data = $this->requestd2p_model->getDetailRequestById($id);
		$mailContent = 
        	'<html>
			<table width="600" style="border: 1px solid black;">
			  <tr>
			    <td width="100%" align="center" bgcolor="#f53b57"><h1 style="color:#ffff;">	
					Reject - '.$data[0]->project_name.' </h1></td>
			  </tr>
			  <tr>
			    <td align="center">
			      <table width="100%" class="table-form">
					
					<tr><td width="25%">Project Name <span style="color:red;"></span></td><td><b>'.$data[0]->project_name.'</b></td></tr>			

					<tr><td width="25%">Project ID <span style="color:red;"></span></td><td><b>'. $data[0]->project_id.'</b></td></tr>
					
					<tr><td width="25%">Project Manager <span style="color:red;"></span></td><td><b>'. $data[0]->project_manager.'</b></td></tr>			
		
					</td></tr>
					<tr>
					<td width="100%" align="center" bgcolor="#5776B7" style="color: #fff;" >This email is generated by stystem, we are not checking the email that have to sent to this email, please kindly open    '.base_url().' for more detailed information.</td>
				</tr>
				</table>   
			  
			</table>
			</html>';

		$to = $data[0]->email;
		$message = $mailContent;
		$subject = 'D2P Reject - '.$data[0]->project_name.'';
		//$this->emailSend($to,$message,$subject);
		$this->view_requestd2p_model->reject_request_d2p($id,$id_role);

		redirect('index.php/view_requestd2p/view_requestd2p_list');
	}

// SEND EMAIL
	
    function emailSend($to,$message,$subject){

        	// Load PHPMailer library
        $this->load->library('phpmailer_lib');
        //$to = $this->session->userdata('email');
        
        // PHPMailer object
        $mail = $this->phpmailer_lib->load();
        
        // SMTP configuration
    
		$mail->IsSMTP();
		$mail->CharSet="UTF-8";
		$mail->SMTPSecure = 'tls';
		$mail->Host = 'smtp.gmail.com';
		$mail->Host = 'tls://smtp.gmail.com:587';
		$mail->Port = 587;
		$mail->Username = 'rizalmdj';
		$mail->Password = 'latitude05106875';
		$mail->SMTPAuth = true;
        
        $mail->setFrom('info@example.com', 'D2P');
        $mail->addReplyTo('info@example.com', 'D2P');
        
        // Add a recipient
        $mail->addAddress($to);
        
        // Add cc or bcc 
        //$mail->addCC('cc@example.com');
        //$mail->addBCC('bcc@example.com');
        
        // Email subject
        $mail->Subject = $subject;
        
        // Set email format to HTML
        $mail->isHTML(true);
        
        // Email body content
        $mail->Body = $message;
        
        // Send email
        if(!$mail->send()){
            echo 'Message could not be sent.';
            echo 'Mailer Error: ' . $mail->ErrorInfo;
        }else{
            echo 'Message has been sent';
        }
    }


}


